export AUR_PACKAGES=(
	arch-wiki-man
	cmake-language-server
	cpupower-gui
	csharp-ls
	fastfetch
	flat-remix
	gnome-shell-pomodoro
	javascript-typescript-langserver
	kcc
	kindlegen
	latex2e-help-texinfo
	makepkg-optimize
	mkinitcpio-firmware
	monophony
	neovim-remote
	nvim-packer-git
	pplatex
	python-re2
	qogir-gtk-theme-git
	ruby-nokogiri
	ttf-unifont
)
