#/usr/bin/env bash
AUR_PACKAGES=(
	#nodejs-docker-langserver
	arch-wiki-man
	bear
	cmake-language-server
	fastfetch-git
	flat-remix
	gnome-shell-pomodoro
	javascript-typescript-langserver
	latex2e-help-texinfo
	neovim-remote
	nerd-fonts-inconsolata-go
	picom-rounded-corners
	polybar
	pplatex
	qogir-gtk-theme-git
	ruby-nokogiri
	sql-language-server
	svls
	texlive-localmanager-git
	ttf-unifont
	zeal
)
