#!/usr/bin/env bash

YADM_PATH="$HOME/.config/yadm"

BEST_MIRROR='Server = https://appuals.com/archlinux/$repo/os/$arch'

# Use the fastest mirror
sudo sed -i "1s#^#$BEST_MIRROR\n#" /etc/pacman.d/mirrorlist

#For less headaches
cd "$HOME"

#Submodules
yadm submodule update --recursive --init

#Installing packages
AUR="paru"

if command -v paru >/dev/null 2>&1; then
	echo "Paru already installed"
else
	sudo pacman -Syu base-devel
	#Paru installation
	pushd /tmp
	git clone https://aur.archlinux.org/$AUR.git
	pushd $AUR
	makepkg -si --noconfirm
	popd
	rm -rf $AUR
	popd
fi

AURARGS=( \
	-Syyu
	--needed
	--nocleanmenu
	--nodiffmenu
	--noeditmenu
	--noupgrademenu
	--noconfirm
)

echo "Installing packages"

source "$YADM_PATH/pacman-packages.sh"
source "$YADM_PATH/aur-packages.sh"

$AUR ${AURARGS[@]} ${PACMAN_PACKAGES[@]} ${AUR_PACKAGES[@]}

#Installing ranger plugin
pushd "$HOME/.config/ranger/plugins/ranger_devicons"
make
popd

#Neovim bootstraping

#Cheking if neovim is installed
if command -v nvim >/dev/null 2>&1; then
	echo "Installing plugins"

	nvim \
		'+PackerSync'\
		'+qall'
fi

# Coc.nvim
pushd ~/.local/share/nvim/site/pack/packer/start/coc.nvim
yarn install
popd
