#!/usr/bin/env bash

WALLPAPER_LINK="https://wallpaperplay.com/walls/full/7/d/2/3508.jpg"
YADM_PATH="$HOME/.config/yadm"

BEST_MIRROR='Server = https://appuals.com/archlinux/$repo/os/$arch'

# Use the fastest mirror
sudo sed -i "1s#^#$BEST_MIRROR\n#" /etc/pacman.d/mirrorlist

#For less headaches
cd "$HOME"

#Submodules
yadm submodule update --recursive --init

#Installing packages

if command -v paru >/dev/null 2>&1; then
	AUR="paru"
	AURARGS=( \
		-Syyu
		--needed
		--nocleanmenu
		--nodiffmenu
		--noeditmenu
		--noupgrademenu
		--noconfirm
	)
else
	echo "Couldn't find paru" >&2
	exit 2
fi

echo "Installing packages"

source "$YADM_PATH/pacman-packages.sh"
source "$YADM_PATH/aur-packages.sh"

$AUR ${AURARGS[@]} ${PACMAN_PACKAGES[@]} ${AUR_PACKAGES[@]}

# Set calibre version
sudo calibre-alternatives set 3

#Downloading wallpaper
curl "$WALLPAPER_LINK" -o "$HOME/.bg.jpg"

#Installing ranger plugin
pushd "$HOME/.config/ranger/plugins/ranger_devicons"
make
popd

#Installing lua packages
sudo luarocks install --server=http://luarocks.org/dev digestif
sudo luarocks install --server=http://luarocks.org/dev lua-lsp

#Installing yarn packages
yarn global add vim-language-server

#Neovim bootstraping

#Cheking if neovim is installed
if command -v nvim >/dev/null 2>&1; then

	echo "Dowloading vimplug"
	curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim \
		--create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

	echo "Installing plugins"

	nvim \
		'+PlugUpdate'\
		'+PlugClean!'\
		'+PlugUpdate'\
		'+qall'
fi
