#/usr/bin/env bash
YAY_PACKAGES=(
	zeal
	polybar
	rxvt-unicode-cvs-patched-wideglyphs
	latex2e-help-texinfo
	nerd-fonts-inconsolata-go
	neovim-remote
	ttf-unifont
	qogir-gtk-theme-git
	flat-remix-git
	minecraft-launcher
	#nodejs-docker-langserver
	bear
	ruby-nokogiri
	texlive-localmanager-git
	arch-wiki-man
	rofi-git
	cmake-language-server
	javascript-typescript-langserver
	urxvt-vtwheel
	paleofetch-git
	picom-rounded-corners
	otf-inconsolata-powerline-git
	svls
	sql-language-server
)
