#!/bin/bash

#For less headaches
cd ${HOME}

#Installing packages

#Arch Linux
if command -v pacman >/dev/null 2>&1; then
	PACMAN="pacman"
	PACINSTALL="-Syu --needed"
else
	echo "Pacman not found" >&2
	exit 1
fi

echo "Installing packages"
xargs -a ${HOME}/.yadm/${PACMAN}-packages sudo ${PACMAN} ${PACINSTALL}

#Vim bootstraping

#Cheking if vim is installed
if command -v vim >/dev/null 2>&1; then
	echo "Installing plugins"

	vim '+source ~/.yadm/plugInstall.vim'\
		'+PlugUpdate'\
		'+PlugClean!'\
		'+PlugUpdate'\
		'+qall'
fi
