#!/bin/bash

#For less headaches
cd ${HOME}

#Submodules
yadm submodule update --recursive --init

#Installing packages

#Arch Linux
if command -v pacman >/dev/null 2>&1; then
	PACMAN="pacman"
	PACINSTALL="-Syu --needed"
else
	echo "Pacman not found" >&2
	exit 1
fi

#Packages in the repositories
echo "Installing packages"
xargs -a ${HOME}/.yadm/${PACMAN}-packages sudo ${PACMAN} ${PACINSTALL}


#Packages in the aur
if command -v yay >/dev/null 2>&1; then
	echo "Yay already installed"
else
	echo "Yay not found" >&2
	echo "Installing yay"

	#Yay installation
	cd /tmp
	git clone https://aur.archlinux.org/yay.git
	cd yay
	makepkg -s
	sudo pacman -U *.pkg.tar.xz
	cd ..
	rm -rf yay
	cd ${HOME}
fi

if command -v yay >/dev/null 2>&1; then
	AUR="yay"
	AURINSTALL="-S --needed"
else
	echo "Couldn't install yay" >&2
	exit 2
fi

xargs -a ${HOME}/.yadm/${AUR}-packages ${AUR} ${AURINSTALL}

#Downloading wallpaper
curl http://i.imgur.com/xOdmlgL.jpg -o ${HOME}/.bg.jpg

#Vim bootstraping

#Cheking if vim is installed
if command -v vim >/dev/null 2>&1; then
	echo "Installing plugins"

	vim '+source ~/.yadm/plugInstall.vim'\
		'+PlugUpdate'\
		'+PlugClean!'\
		'+PlugUpdate'\
		'+qall'
fi

#Installing ranger plugin
cd ${HOME}/.config/ranger/plugins/ranger_devicons
make
cd ${HOME}
#Installing lua packages
sudo luarocks install --server=http://luarocks.org/dev digestif
sudo luarocks install --server=http://luarocks.org/dev lua-lsp

#Installing yarn packages
yarn global add vim-language-server

#Neovim bootstraping

#Because a bug that inserts text on neovim, this doesn't work.
#Cheking if neovim is installed
if command -v nvim >/dev/null 2>&1; then
	echo "Installing plugins"

		nvim \
			'+PlugUpdate'\
			'+PlugClean!'\
			'+PlugUpdate'\
			'+qall'
fi
